apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agenda
  template:
    metadata:
      labels:
        app: agenda
    spec:
      containers:
      - name: agenda
        image: goltaraya/agenda:v6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agenda
spec:
  selector:
    app: agenda
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort